### ISSUE TITLE
opt.name 改为 opt.uname

### ISSUE THREAD

**Issue by 252509701** [yuncreate/egoal-ticket-api#3]
// verify uname（检测账号）
    if(opt.uname == undefined || trim(opt.uname) == ""){
        throw new Error('uname required.');
    }

**Comment by mengkeys** [comment]
@252509701 已经修复 #2

**Comment by mengkeys** [comment]
@252509701 重新执行以下命令即可
```
npm install egoal-ticket-api --save
```
